# Generated by Django 6.0.5 on 2026-06-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillplatform', '0002_alter_aigeneration_user_alter_chatmessage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
    ]
